name: Tag Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-release:
    uses: sweetrpg/github-actions/.github/workflows/rust-tag-release.yaml@master
    with:
      release-branch: main
    secrets:
      SRPG_CI_APP_ID: ${{ secrets.SKWAD_CI_APP_ID }}
      SRPG_CI_PRIVATE_KEY: ${{ secrets.SKWAD_CI_PRIVATE_KEY }}
